Repository goravel/fiber, pull requests merged in 2023-11, with the labels that each got.

#33 feat: [#294] Validator cant check the param of url
  context_request.go
  context_request_test.go
Labels: 🚀 Review Ready

#34 feat: support http.ResponseWriter and optimize content type
  context_response.go
  context_response_test.go
  response.go
Labels: ☢️ Bug, 🚀 Review Ready

#35 fix: file methods and GlobalMiddleware method
  group.go
  group_test.go
  response.go
  route.go
Labels: ☢️ Bug, 🚀 Review Ready

#42 fix: fallback the logic of GlobalMiddleware
  .goreleaser.yaml
  context_request.go
  group.go
  group_test.go
  route.go
Labels: ☢️ Bug

#38 feat: fiber support filter tag
  README.md
  context_request.go
  context_request_test.go
  context_response_test.go
  cors_test.go
  go.mod
  go.sum
  group_test.go
  route.go
  route_test.go
  view_test.go
Labels: ❗ Breaking Change, ✏️ Feature, 🚀 Review Ready
